//HintName: Enums.EnumScribe.g.cs
// <autogenerated/>
#nullable enable
using System.Runtime.CompilerServices;

namespace EnumScribe.Extensions
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("EnumScribe", "1.1.1")]
    public static class EnumDescriptions
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static string DescriptionText(this TestCode.StockLevel e) => e switch
        {
            TestCode.StockLevel.Available => "In stock",
            TestCode.StockLevel.Low => "Low stock",
            TestCode.StockLevel.OutOfStock => "Out of stock",
            TestCode.StockLevel.Retired => "Unavailable",
            _ => string.Empty,
        };
    }
}
#nullable restore
