//HintName: Partials.EnumScribe.g.cs
// <autogenerated/>
#nullable enable
using EnumScribe.Extensions;

namespace TestCode
{
    partial class Inventory
    {
        public string? CakeStockDescription => CakeStock?.DescriptionText();
        internal string FishStockDescription => FishStock.DescriptionText();
    }
}
#nullable restore
