name: "NuGet Publish"

on:
  workflow_dispatch:

# TODO: Split up workflows properly - v hackjob-y

jobs:
  nuget-publish:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET 6.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
        env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_API_KEY}}

      - name: Restore
        run: dotnet restore
        
      - name: Build
        run: dotnet build -c Release --no-restore
        
      - name: Publish
        # TODO: Fix dodgy hardcoding (along with the rest of this publish pipeline)
        run: |
          mkdir __out
          dotnet pack -c Release -o __out --no-restore
          dotnet nuget push "./__out/EnumScribe.1.1.1.nupkg" --source "https://api.nuget.org/v3/index.json" --skip-duplicate --no-symbols true --api-key ${{secrets.NUGET_API_KEY}}
          rm __out -Recurse -Force
